# Generated by Django 2.0.2 on 2019-09-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20190913_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=1, default=0, editable=False, max_digits=4),
        ),
    ]
